---
AWSTemplateFormatVersion: '2010-09-09'
Description: >
  DNS nested stack.

Parameters:
  VPC:
    Type: String
Resources:

  ServiceDiscoveryJenkinsMasterNamespace:
    Type: AWS::ServiceDiscovery::PrivateDnsNamespace
    Properties:
      Vpc: !Ref VPC
      Name: jenkins.local

  ServiceDiscoveryJenkinsMaster:
    Type: AWS::ServiceDiscovery::Service
    Properties:
      Description: Jenkins Master Service
      DnsConfig:
        DnsRecords:
        - Type: A
          TTL: 60
        NamespaceId: !Ref ServiceDiscoveryJenkinsMasterNamespace
      HealthCheckCustomConfig:
        FailureThreshold: 1
      Name: master

Outputs:
  ServiceDiscoveryJenkinsMaster:
    Value: !GetAtt ServiceDiscoveryJenkinsMaster.Arn