---
AWSTemplateFormatVersion: '2010-09-09'

Description: >
  ECS nested stack

Resources:

  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: MW-MGM-ECSCluster

Outputs:
  ECSCluster:
    Value: !GetAtt ECSCluster.Arn